import type { ThemeConfig } from './types'

export const adhd: ThemeConfig = {
  id: 'adhd',
  name: 'ADHD Planner',
  tagline: 'Work with your brain, not against it.',
  appTitle: 'ADHD Planner',
  defaultDarkMode: false,
  colors: {
    primary: '#2563EB',
    primaryDim: 'rgba(37, 99, 235, 0.15)',
    bg: '#F8FAFF',
    surface: '#FFFFFF',
    surfaceAlt: '#EFF6FF',
    text: '#0F172A',
    textMuted: 'rgba(15, 23, 42, 0.5)',
    accent: '#F59E0B',
    accent2: '#10B981',
    border: 'rgba(37, 99, 235, 0.2)',
    danger: '#EF4444',
    success: '#10B981',
  },
  fonts: {
    display: 'DM Sans',
    body: 'DM Sans',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap',
  },
  features: {
    sessions: true,
    contacts: false,
    accounts: false,
    scripts: true,
    emailTemplates: false,
    pipeline: false,
    goals: true,
    analytics: true,
    team: false,
    activityFeed: true,
    dailyReflection: true,
    affirmations: false,
    horoscope: false,
    hyperfocusTimer: true,
    workoutLog: false,
    weightTracker: false,
    caregiverLog: false,
  },
  labels: {
    sessionName: 'Focus Sprint',
    sessionNamePlural: 'Focus Sprints',
    contactsName: 'People',
    scriptsName: 'Checklists',
    dashboardTitle: "Today's Plan",
    dashboardGreeting: 'Let\'s get going,',
    shortName: 'AP',
    fullName: 'ADHD Planner',
  },
}
