import type { ThemeConfig } from './types'

export const athlete: ThemeConfig = {
  id: 'athlete',
  name: 'Athlete Planner',
  tagline: 'Train harder. Recover smarter. Win.',
  appTitle: 'Athlete Planner',
  defaultDarkMode: true,
  colors: {
    primary: '#DC2626',
    primaryDim: 'rgba(220, 38, 38, 0.15)',
    bg: '#0A0A0A',
    surface: '#141414',
    surfaceAlt: '#1C1C1C',
    text: '#F5F5F5',
    textMuted: 'rgba(245, 245, 245, 0.5)',
    accent: '#F59E0B',
    accent2: '#6366F1',
    border: 'rgba(220, 38, 38, 0.2)',
    danger: '#EF4444',
    success: '#22C55E',
  },
  fonts: {
    display: 'Barlow Condensed',
    body: 'Barlow',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;500;600;700;800&family=Barlow:wght@300;400;500;600&display=swap',
  },
  features: {
    sessions: true,
    contacts: false,
    accounts: false,
    scripts: true,
    emailTemplates: false,
    pipeline: false,
    goals: true,
    analytics: true,
    team: true,
    activityFeed: true,
    dailyReflection: true,
    affirmations: false,
    horoscope: false,
    hyperfocusTimer: false,
    workoutLog: true,
    weightTracker: false,
    caregiverLog: false,
  },
  labels: {
    sessionName: 'Training Block',
    sessionNamePlural: 'Training Blocks',
    contactsName: 'Teammates',
    scriptsName: 'Game Plans',
    dashboardTitle: 'Game Day',
    dashboardGreeting: 'Ready to compete,',
    shortName: 'AT',
    fullName: 'Athlete Planner',
  },
}
