import type { ThemeConfig } from './types'

export const caring: ThemeConfig = {
  id: 'caring',
  name: 'Caring for Others Planner',
  tagline: 'Caring for others starts with caring for you.',
  appTitle: 'Caring Planner',
  defaultDarkMode: false,
  colors: {
    primary: '#0D9488',
    primaryDim: 'rgba(13, 148, 136, 0.15)',
    bg: '#F0FDF9',
    surface: '#FFFFFF',
    surfaceAlt: '#CCFBF1',
    text: '#134E4A',
    textMuted: 'rgba(19, 78, 74, 0.5)',
    accent: '#F97316',
    accent2: '#8B5CF6',
    border: 'rgba(13, 148, 136, 0.2)',
    danger: '#F43F5E',
    success: '#22C55E',
  },
  fonts: {
    display: 'Nunito',
    body: 'Nunito',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700&display=swap',
  },
  features: {
    sessions: true,
    contacts: true,
    accounts: false,
    scripts: true,
    emailTemplates: false,
    pipeline: false,
    goals: true,
    analytics: false,
    team: true,
    activityFeed: true,
    dailyReflection: true,
    affirmations: false,
    horoscope: false,
    hyperfocusTimer: false,
    workoutLog: false,
    weightTracker: false,
    caregiverLog: true,
  },
  labels: {
    sessionName: 'Care Session',
    sessionNamePlural: 'Care Sessions',
    contactsName: 'People I Care For',
    scriptsName: 'Care Notes',
    dashboardTitle: 'Your Day',
    dashboardGreeting: 'Hello,',
    shortName: 'CP',
    fullName: 'Caring Planner',
  },
}
