import type { ThemeConfig } from './types'

export const manifestation: ThemeConfig = {
  id: 'manifestation',
  name: 'Manifestation Planner',
  tagline: 'What you believe, you can achieve.',
  appTitle: 'Manifestation Planner',
  defaultDarkMode: true,
  colors: {
    primary: '#C084FC',
    primaryDim: 'rgba(192, 132, 252, 0.15)',
    bg: '#0D0A1A',
    surface: '#130F24',
    surfaceAlt: '#1A1530',
    text: '#F3E8FF',
    textMuted: 'rgba(243, 232, 255, 0.5)',
    accent: '#F9A8D4',
    accent2: '#818CF8',
    border: 'rgba(192, 132, 252, 0.2)',
    danger: '#FB7185',
    success: '#34D399',
  },
  fonts: {
    display: 'Playfair Display',
    body: 'Nunito',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&family=Nunito:wght@300;400;600;700&display=swap',
  },
  features: {
    sessions: true,
    contacts: false,
    accounts: false,
    scripts: true,
    emailTemplates: false,
    pipeline: false,
    goals: true,
    analytics: true,
    team: false,
    activityFeed: true,
    dailyReflection: true,
    affirmations: true,
    horoscope: false,
    hyperfocusTimer: false,
    workoutLog: false,
    weightTracker: false,
    caregiverLog: false,
  },
  labels: {
    sessionName: 'Intention Block',
    sessionNamePlural: 'Intention Blocks',
    contactsName: 'Connections',
    scriptsName: 'Affirmations',
    dashboardTitle: 'Your Journey',
    dashboardGreeting: 'You are aligned,',
    shortName: 'MP',
    fullName: 'Manifestation Planner',
  },
}
