import type { ThemeConfig } from './types'

export const salesplanner: ThemeConfig = {
  id: 'salesplanner',
  name: 'SalesPlanner',
  tagline: 'Your sales productivity engine.',
  appTitle: 'SalesBlock.io',
  defaultDarkMode: true,
  colors: {
    primary: '#6366F1',
    primaryDim: 'rgba(99, 102, 241, 0.15)',
    bg: '#020617',
    surface: '#0F172A',
    surfaceAlt: '#131f24',
    text: '#F8FAFC',
    textMuted: 'rgba(248, 250, 252, 0.5)',
    accent: '#0db9f2',
    accent2: '#8b5cf6',
    border: 'rgba(255, 255, 255, 0.1)',
    danger: '#f43f5e',
    success: '#10b981',
  },
  fonts: {
    display: 'Space Grotesk',
    body: 'Inter',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&family=Inter:wght@300;400;500;600;700&display=swap',
  },
  features: {
    sessions: true,
    contacts: true,
    accounts: true,
    scripts: true,
    emailTemplates: true,
    pipeline: true,
    goals: true,
    analytics: true,
    team: true,
    activityFeed: true,
    dailyReflection: false,
    affirmations: false,
    horoscope: false,
    hyperfocusTimer: false,
    workoutLog: false,
    weightTracker: false,
    caregiverLog: false,
  },
  labels: {
    sessionName: 'SalesBlock',
    sessionNamePlural: 'SalesBlocks',
    contactsName: 'Contacts',
    scriptsName: 'Scripts',
    dashboardTitle: 'Dashboard',
    dashboardGreeting: 'Good morning,',
    shortName: 'SB',
    fullName: 'SalesBlock.io',
  },
}
