import type { ThemeConfig } from './types'

export const starSign: ThemeConfig = {
  id: 'star-sign',
  name: 'Star Sign Planner',
  tagline: 'Align with the cosmos.',
  appTitle: 'Star Sign Planner',
  defaultDarkMode: true,
  colors: {
    primary: '#F59E0B',
    primaryDim: 'rgba(245, 158, 11, 0.15)',
    bg: '#05061A',
    surface: '#0A0C2A',
    surfaceAlt: '#0F1235',
    text: '#EEF2FF',
    textMuted: 'rgba(238, 242, 255, 0.5)',
    accent: '#60A5FA',
    accent2: '#A78BFA',
    border: 'rgba(245, 158, 11, 0.2)',
    danger: '#F87171',
    success: '#4ADE80',
  },
  fonts: {
    display: 'Cinzel',
    body: 'Raleway',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Cinzel:wght@400;500;600;700&family=Raleway:wght@300;400;500;600&display=swap',
  },
  features: {
    sessions: true,
    contacts: false,
    accounts: false,
    scripts: false,
    emailTemplates: false,
    pipeline: false,
    goals: true,
    analytics: true,
    team: false,
    activityFeed: true,
    dailyReflection: true,
    affirmations: false,
    horoscope: true,
    hyperfocusTimer: false,
    workoutLog: false,
    weightTracker: false,
    caregiverLog: false,
  },
  labels: {
    sessionName: 'Cosmic Session',
    sessionNamePlural: 'Cosmic Sessions',
    contactsName: 'Connections',
    scriptsName: 'Rituals',
    dashboardTitle: 'Your Stars Today',
    dashboardGreeting: 'The stars shine for you,',
    shortName: 'SS',
    fullName: 'Star Sign Planner',
  },
}
