import type { ThemeConfig } from './types'

export const stoic: ThemeConfig = {
  id: 'stoic',
  name: 'Stoic Planner',
  tagline: 'Discipline is freedom.',
  appTitle: 'Stoic Planner',
  defaultDarkMode: true,
  colors: {
    primary: '#C9A84C',
    primaryDim: 'rgba(201, 168, 76, 0.15)',
    bg: '#0A0A0F',
    surface: '#111118',
    surfaceAlt: '#18181F',
    text: '#E8E3D5',
    textMuted: 'rgba(232, 227, 213, 0.5)',
    accent: '#8B7355',
    accent2: '#6B5B3E',
    border: 'rgba(201, 168, 76, 0.15)',
    danger: '#C0392B',
    success: '#27AE60',
  },
  fonts: {
    display: 'Cormorant Garamond',
    body: 'Lato',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;500;600;700&family=Lato:wght@300;400;700&display=swap',
  },
  features: {
    sessions: true,
    contacts: false,
    accounts: false,
    scripts: true,
    emailTemplates: false,
    pipeline: false,
    goals: true,
    analytics: true,
    team: false,
    activityFeed: true,
    dailyReflection: true,
    affirmations: false,
    horoscope: false,
    hyperfocusTimer: false,
    workoutLog: false,
    weightTracker: false,
    caregiverLog: false,
  },
  labels: {
    sessionName: 'Focus Block',
    sessionNamePlural: 'Focus Blocks',
    contactsName: 'People',
    scriptsName: 'Meditations',
    dashboardTitle: 'Today',
    dashboardGreeting: 'Welcome,',
    shortName: 'SP',
    fullName: 'Stoic Planner',
  },
}
