import type { ThemeConfig } from './types'

export const weightLoss: ThemeConfig = {
  id: 'weight-loss',
  name: 'Weight Loss Planner',
  tagline: 'Small steps. Big changes.',
  appTitle: 'Weight Loss Planner',
  defaultDarkMode: false,
  colors: {
    primary: '#16A34A',
    primaryDim: 'rgba(22, 163, 74, 0.15)',
    bg: '#F0FDF4',
    surface: '#FFFFFF',
    surfaceAlt: '#DCFCE7',
    text: '#14532D',
    textMuted: 'rgba(20, 83, 45, 0.5)',
    accent: '#F97316',
    accent2: '#06B6D4',
    border: 'rgba(22, 163, 74, 0.2)',
    danger: '#EF4444',
    success: '#22C55E',
  },
  fonts: {
    display: 'Poppins',
    body: 'Poppins',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap',
  },
  features: {
    sessions: true,
    contacts: false,
    accounts: false,
    scripts: true,
    emailTemplates: false,
    pipeline: false,
    goals: true,
    analytics: true,
    team: false,
    activityFeed: true,
    dailyReflection: true,
    affirmations: true,
    horoscope: false,
    hyperfocusTimer: false,
    workoutLog: true,
    weightTracker: true,
    caregiverLog: false,
  },
  labels: {
    sessionName: 'Wellness Session',
    sessionNamePlural: 'Wellness Sessions',
    contactsName: 'Supporters',
    scriptsName: 'Healthy Habits',
    dashboardTitle: 'Your Progress',
    dashboardGreeting: 'Keep going,',
    shortName: 'WL',
    fullName: 'Weight Loss Planner',
  },
}
